### ISSUE TITLE
Composer fails on missing dependency

### ISSUE THREAD

**Issue by ajthenewguy** [digitalkaoz/versioneye-php#10]
`$ composer require digitalkaoz/versioneye-php`
Results in "Your requirements could not be resolved to an installable set of packages."

```
- Installation request for digitalkaoz/versioneye-php ^0.11.2 -> satisfiable by digitalkaoz/versioneye-php[0.11.2].
- digitalkaoz/versioneye-php 0.11.2 requires rybakit/arguments-resolver 1.0.x-dev@dev -> no matching package found.
```

**Comment by mattsches** [comment]
This might have been fixed by https://github.com/digitalkaoz/versioneye-php/pull/11

**Comment by digitalkaoz** [comment]
@ajthenewguy is it fixed when installing `0.11.3` ?

**Comment by ajthenewguy** [comment]
Hey guys; yes this fixed it. Thanks.
Note: I got the following warning: "Package egeloen/http-adapter is abandoned, you should avoid using it. Use php-http/httplug instead".

**Comment by digitalkaoz** [comment]
I already have a branch to fix this

Allen McCabe <notifications@github.com> schrieb am Mi., 30. März 2016,
16:34:
