### ISSUE TITLE
DocBlock::getShortDescription not existent in "phpdocumentor/reflection-docblock": "~3.0"

### ISSUE THREAD

**Issue by ickbinhier** [digitalkaoz/versioneye-php#15]
PHP Fatal error:  Uncaught Error: Call to undefined method phpDocumentor\Reflection\DocBlock::getShortDescription() in /var/www/html/vendor/digitalkaoz/versioneye-php/src/Console/CommandFactory.php:85
Stack trace:
#0 /var/www/html/vendor/digitalkaoz/versioneye-php/src/Console/CommandFactory.php(59): Rs\VersionEye\Console\CommandFactory->generateCommand('Github', Object(ReflectionMethod), NULL)
#1 /var/www/html/vendor/digitalkaoz/versioneye-php/bin/versioneye(29): Rs\VersionEye\Console\CommandFactory->generateCommands()
#2 {main}
  thrown in /var/www/html/vendor/digitalkaoz/versioneye-php/src/Console/CommandFactory.php on line 85

**Comment by digitalkaoz** [comment]
mh maybe it was removed in a recent version, ill investigate that

**Comment by digitalkaoz** [comment]
@ickbinhier its fixed in current master and `1.0.0` can you check it?
