### ISSUE TITLE
Package egeloen/http-adapter is abandoned, you should avoid using it. Use php-http/httplug instead.

### ISSUE THREAD

**Issue by w3l** [digitalkaoz/versioneye-php#9]
^^

**Comment by tubssp** [comment]
+1

**Comment by digitalkaoz** [comment]
im working on it, maybe i finish it this weekend.

Andreas Lemke <notifications@github.com> schrieb am Fr., 19. Feb. 2016 um
06:03 Uhr:

**Comment by digitalkaoz** [comment]
fixed in master and `1.0.0`
